language: php

services:
  - mysql
  - postgresql

cache:
  directories:
    - $HOME/.composer/cache/files

branches:
  only:
    - master

env:
  global:
    - DB_NAME="testdb"

# Aim to run tests on all versions of php, make sure each db is run at least once
matrix:
  include:
    - php: 5.5
      env: DB="postgresql" DB_USER="postgres"
    - php: 5.6
      env: DB="mysql" DB_USER="root"
    - php: 7.0
      env: DB="postgresql" DB_USER="postgres"
    - php: 7.1
      env: DB="mysql" DB_USER="root"
# Will need to update phpunit for this: https://travis-ci.org/ezsystems/ezpublish-legacy/jobs/279543965#L625
#    - php: 7.2
#      env: DB="postgresql" DB_USER="postgres"

before_script:
  - if [ $DB == "mysql" ]; then mysql -e "CREATE DATABASE IF NOT EXISTS $DB_NAME;" -u$DB_USER ; fi
  - if [ $DB == "postgresql" ]; then psql -c "CREATE DATABASE $DB_NAME;" -U $DB_USER ; psql -c "CREATE EXTENSION pgcrypto;" -U $DB_USER $DB_NAME ; fi
  - composer install --prefer-source
  - php bin/php/ezpgenerateautoloads.php -s -e
  # Detecting timezone issues by testing on random timezone
  - TEST_TIMEZONES=("America/New_York" "Asia/Calcutta" "UTC")
  - TEST_TIMEZONE=${TEST_TIMEZONES["`shuf -i 0-2 -n 1`"]}
  - echo "$TEST_TIMEZONE"

script:
  - php -d date.timezone=$TEST_TIMEZONE tests/runtests.php --dsn "$DB://${DB_USER}@127.0.0.1/$DB_NAME" tests extension/ezoe

notification:
  email: false

git:
  depth: 30
