language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

branches:
  only:
    - master

env:
  global:
    - DB_NAME="testdb"
  matrix:
    - DB="mysql" DB_USER="root"
    - DB="postgresql" DB_USER="postgres"

# Aim to run tests on all versions of php, make sure each db is run at least once
matrix:
  exclude:
    - php: 5.3.3
      env: DB="postgresql" DB_USER="postgres"
    - php: 5.3
      env: DB="mysql" DB_USER="root"
    - php: 5.4
      env: DB="postgresql" DB_USER="postgres"
    - php: 5.5
      env: DB="mysql" DB_USER="root"

before_script:
 - if [ $DB == "mysql" ]; then mysql -e "CREATE DATABASE IF NOT EXISTS $DB_NAME;" -u$DB_USER ; fi
 - if [ $DB == "postgresql" ]; then psql -c "CREATE DATABASE $DB_NAME;" -U $DB_USER ; psql -c "CREATE EXTENSION pgcrypto;" -U $DB_USER $DB_NAME ; fi
 - composer install --prefer-source
 - php bin/php/ezpgenerateautoloads.php -s -e
 # Detecting timezone issues by testing on random timezone
 - declare -a TIMEZONES=("America/New_York" "Asia/Calcutta" "UTC")
 - declare -a TIMEZONE=${TIMEZONES["`shuf -i 0-2 -n 1`"]}


script:
  - php -d date.timezone=$TIMEZONE tests/runtests.php --debug --dsn "$DB://${DB_USER}@127.0.0.1/$DB_NAME"

notification:
  email: false

git:
  depth: 30
