language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

branches:
  only:
    - master

env:
  global:
    - DB_NAME="testdb"
  matrix:
    - DB="mysql" DB_USER="root" TIMEZONE="Asia/Calcutta"
    - DB="mysql" DB_USER="root" TIMEZONE="America/New_York"
    - DB="postgresql" DB_USER="postgres" TIMEZONE="Asia/Calcutta"

matrix:
  exclude:
    - php: 5.3
      env: DB="mysql" DB_USER="root" TIMEZONE="America/New_York"
    - php: 5.4
      env: DB="mysql" DB_USER="root" TIMEZONE="Asia/Calcutta"
    - php: 5.4
      env: DB="postgres" DB_USER="postgres" TIMEZONE="Asia/Calcutta"
    - php: 5.5
      env: DB="mysql" DB_USER="root" TIMEZONE="America/New_York"

before_script:
 - if [ $DB == "mysql" ]; then mysql -e "CREATE DATABASE IF NOT EXISTS $DB_NAME;" -u$DB_USER ; fi
 - if [ $DB == "postgresql" ]; then psql -c "CREATE DATABASE $DB_NAME;" -U $DB_USER ; psql -c "CREATE EXTENSION pgcrypto;" -U $DB_USER $DB_NAME ; fi
 - php bin/php/ezpgenerateautoloads.php -s -e
 - cp config.php-TRAVIS config.php
 - composer install --prefer-source

script:
  - php -d date.timezone=$TIMEZONE tests/runtests.php --dsn "$DB://${DB_USER}@127.0.0.1/$DB_NAME"

notification:
  email: false

git:
  depth: 30
